---
language: python
python: "3.6"
dist: trusty
sudo: required
group: edge

services:
- docker

before_install:
- sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty-backports universe'
- sudo apt-get update -qq

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg



script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/





install:
- pip install https://github.com/ansible/ansible/archive/devel.tar.gz
- pip install -e git+https://github.com/ansible/ansible-container.git@develop#egg=ansible_container[docker]
script:
- docker version
- docker-compose version
- docker info
- cd test
- mkdir demo
- cd demo
- ansible-container init ansible.django-gulp-nginx
- cp -R ../../src/* src
- cp -R ../../project/* project
- ansible-container build
- ansible-container run
- docker ps -a
- docker images
- cd ..
- ansible-playbook -i inventory test.yml
- cd demo
- ansible-container stop -f