sudo: required
dist: trusty
language: python
python:
  - "3.6"

services:
  - docker

jobs:
  include:
    - stage: Setup environment
      script:

        - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty-backports universe'
        - sudo apt-get update -qq

        - docker --version

        # Add docker edge
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
        - sudo apt-get update
        - sudo apt-get -y install docker-ce

        - docker --version

        # Setup docker experimental
        - echo '{"experimental":"enabled"}' > config.json

        - docker --version
        - docker-compose version

        # Setup Ansible-Container
        - pip install https://github.com/ansible/ansible/archive/devel.tar.gz
        - pip install -e git+https://github.com/ansible/ansible-container.git@develop#egg=ansible_container[docker]

    - stage: Build service images

      env:
        - RCD_ARCH=amd64
        - RCD_ARCH=armv7hf

      script:

          # Build it
        - cd ansible-containers/base
        - pwd

        - echo $RCD_ARCH

    - stage: deploy
      script:

        # Only want to do this _once_ at the end

        # Login to docker, retag, manifest, and push
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

        # Need to put docker on experimental to have access to manifest...
        - python manifest-it.py -m -d rcd-manifests.yml



#
## Build amd64 containers
#- export RCD_ARCH=amd64
#
## Get working conductor
#- docker pull rcdiana/container-conductor-resin-${RCD_ARCH}-stretch:0.9.3rc0
#- docker tag rcdiana/container-conductor-resin-${RCD_ARCH}-stretch:0.9.3rc0 container-conductor-resin-${RCD_ARCH}-stretch:0.9.3rc0
#
#- sed -E -i "s/(amd64)|(armv7hf)/$RCD_ARCH/" container.yml  # Replace settings arches
#- ansible-container build
#
## Build armv7hf containers
#- export RCD_ARCH=armv7hf
#
## Get working conductor
#- docker pull rcdiana/container-conductor-resin-${RCD_ARCH}-stretch:0.9.3rc0
#- docker tag rcdiana/container-conductor-resin-${RCD_ARCH}-stretch:0.9.3rc0 container-conductor-resin-${RCD_ARCH}-stretch:0.9.3rc0
#
#- sed -E -i "s/(amd64)|(armv7hf)/$RCD_ARCH/" container.yml  # Replace settings arches
#- ansible-container build
#
### Run it
##- ansible-container run
##- docker ps -a
##- docker images
##- ansible-container stop -f



#jobs:
#  include:
#    - stage:
#        if: env(BUILD_CONDUCTORS)
#        name: build_conductors
#        script:
#          - cd $TRAVIS_BUILD_DIR/ansible-containers/conductors && docker-compose build
#
#          # Login to docker for push
#          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#
#          # Push conductors for reference
##          - docker tag container-conductor-resin-amd64-stretch:0.9.3rc0 rcdiana/container-conductor-resin-amd64-stretch:0.9.3rc0
##          - docker push rcdiana/container-conductor-resin-amd64-stretch:0.9.3rc0
#
#          - docker tag container-conductor-resin-armv7hf-stretch:0.9.3rc0 rcdiana/container-conductor-resin-armv7hf-stretch:0.9.3rc0
#          - docker push rcdiana/container-conductor-resin-armv7hf-stretch:0.9.3rc0
#