sudo: required

language: python
python:
    - "3.6"

services:
  - docker

env:
  BUILD_CONDUCTORS: false
  BUILD_AMD64: true
  BUILD_ARMV7HF: false

jobs:
  include:
    - stage:
        if: env(BUILD_CONDUCTORS)
        name: build_conductors
        script:
          - cd $TRAVIS_BUILD_DIR/ansible-containers/conductors && docker-compose build

          # Login to docker for push
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

          # Push conductors for reference
          - docker tag container-conductor-resin-amd64-stretch:0.9.3rc0 rcdiana/container-conductor-resin-amd64-stretch:0.9.3rc0
          - docker push rcdiana/container-conductor-resin-amd64-stretch:0.9.3rc0

          - docker tag container-conductor-resin-armv7hf-stretch:0.9.3rc0 rcdiana/container-conductor-resin-armv7hf-stretch:0.9.3rc0
          - docker push rcdiana/container-conductor-resin-armv7hf-stretch:0.9.3rc0

    - stage:
      if: env(BUILD_AMD64)
      name: build_amd64
      script:
        # Setup conductor
        - docker pull rcdiana/container-conductor-resin-amd64-stretch:0.9.3rc0
        - docker tag rcdiana/container-conductor-resin-amd64-stretch:0.9.3rc0 container-conductor-resin-amd64-stretch:0.9.3rc0

        # Build containers
        - cd $TRAVIS_BUILD_DIR/ansible-containers/base && ansible-container build

                # Login to docker for push
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - cd $TRAVIS_BUILD_DIR/ansible-containers/base && python tag_and_manifest.py



