# rcDiana simple service setup

# rcdiana is multiarch, so this is typically sufficient for a manual install
# on either amd64 (intel) or armc7hf (raspberry pi)

# On resin may need to add ":armv7h" tags for raspberry pi b/c the uploader is
# arm64 and will try to grab arm64 by preference rather that the target arch.

version: '2.1'

services:

  dicom:
    image: rcdiana/dicom:armv7hf
    restart: always
    privileged: true
    ports:
      - "4242:4242"
      - "80:8042"  # Putting this on 80 makes it publishable on Resin

  learn:
    image: rcdiana/learn:armv7hf
    restart: always
    privileged: true
    links:
      - "dicom:dicom"

