# Project builder for resin.io devices
# rcdiana is multiarch, so no need to configure further!

version: '2.1'

services:

  dicom:
    image: rcdiana/dicom
    restart: always
    privileged: true
    ports:
      - "4242:4242"
      - "80:8042"  # Putting this on 80 makes it publishable on Resin

  python:
    image: rcdiana/python
    restart: always
    privileged: true


