# Project builder for resin.io devices
# rcdiana is multiarch, so no need to configure further!

version: '2.1'

services:

  dicom:
    image: rcdiana/dicom:amd64
    restart: always
    privileged: true
    ports:
      - "4242:4242"
      - "8042:8042"

  python:
    image: rcdiana/python:amd64
    restart: always
    privileged: true


