---
# tasks file for flask


- name: Create flask user
  user:
    name: flask
    uid: 1000
    group: root
    state: present
    createhome: yes
    home: "/app"
- name: Copy source into container
  synchronize:
    src: "src/"
    dest: "/app"
  remote_user: flask
- name: Install Python dependencies
  pip:
    requirements: /app/requirements.txt