# Base should be stretch

- name: Add system reqs
  package:
    name:
      - build-essential
      - sed
      - sudo
      - tar
      - udev
      - wget
      - git
      - python3-dev
      - python3-numpy-dev
      - python3-setuptools
      - python3-pip
      - python-setuptools
    install_recommends: no
    autoclean: yes

- shell: pip3 install -U pip && pip2 install -U pip

- shell: pip3 --version
  register: result

- debug: var=result

- shell: pip2 --version
  register: result

- debug: var=result

- git:
    repo: 'https://github.com/movidius/ncsdk'
    dest: /ncsdk2
    version: ncsdk2
    force: yes

# Edit the wrong-os fail states out of make install
- shell: sed -i 's/exit 1//g' /ncsdk2/install.sh

# Run the installer
- make:
    chdir: /ncsdk2
    target: install
