---
# tasks file for tensorflow

- name: Add system reqs
  package:
    name:
      - build-essential
#      - libopenblas-base  # numpy seems to get this for you
      - python2.7-dev
    install_recommends: no
    autoclean: yes

- name: Add as many conda reqs as possible
  shell: /opt/conda/bin/conda install -y numpy mock werkzeug
# tensorboard and bleach have a particular requirement for html5lib, so let pip handle it

#- name: Add pip reqs with --no-cache-dir
#  pip:
#    name:
#      - tensorboard
#      - astor
#      - grpcio
#      - markdown
#      - futures
#      - enum34
#      - gast
#      - ruamel.yaml
#      - absl-py
#      - six
#      - termcolor
#      - protobuf
#      - backports.weakref
#    extra_args: "--no-cache-dir"
#    executable: /opt/conda/bin/pip

- set_fact:
    TENSORFLOW_VERSION: "1.7.0"
    TENSORFLOW_DEVICE: "cpu"
  when: RCD_ARCH=="amd64"
  # Less control over armv7hf last successful build

- set_fact:
    TF_PKG: "https://storage.googleapis.com/tensorflow/linux/{{TENSORFLOW_DEVICE}}/tensorflow-{{TENSORFLOW_VERSION}}-cp27-none-linux_x86_64.whl"
  when: RCD_ARCH=="amd64"

- set_fact:
# Last good rpi buid
    TF_PKG: "http://ci.tensorflow.org/view/Nightly/job/nightly-pi/lastSuccessfulBuild/artifact/output-artifacts/tensorflow-1.7.0-cp27-none-any.whl"
# Older and doesn't install clean
#    TF_PKG: "https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases/download/v1.1.0/tensorflow-1.1.0-cp27-none-linux_armv7l.whl"
  when: RCD_ARCH=="armv7hf"

- name: Install TensorFlow
  pip:
    name: "{{ TF_PKG }}"
    extra_args: "--no-cache-dir"
    executable: /opt/conda/bin/pip

- name: Reinstall mock
  shell: /opt/conda/bin/conda install -y --force mock

- name: Get rid of TensorFlow warnings
  lineinfile:
    name: ~/.bashrc
    line: "export TF_CPP_MIN_LOG_LEVEL=2"
    create: true
#  when: RCD_ARCH=="amd64"
