---
# tasks file for tensorflow

- set_facts:
    TENSORFLOW_VERSION: 1.5.0
    TENSORFLOW_DEVICE: cpu

- pip: Install TF
    name: "https://storage.googleapis.com/tensorflow/linux/{{ TENSORFLOW_DEVICE }}/tensorflow-{{ TENSORFLOW_VERSION }}-cp27-none-linux_x86_64.whl"
    extra_args: "--no-cache-dir --ignore-installed --upgrade"