---
# tasks file for common

- debug:
    msg: "Setting up common services for {{ RCD_ARCH }}"

- debug:
    msg: "Changing root password to {{ ROOT_PASSWORD }}"

- name: change password for root user
  become: true # do this as root
  user:
    name: root
    password: "{{ ROOT_PASSWORD }}"

- name: Install dumb init
  get_url:
    dest: /usr/bin/dumb-init
    url: https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64
    mode: 0775
    validate_certs: no

- name: Update apt-cache
  apt:
    name:
    update_cache: true

