---
# tasks file for keras

# These should already be present from tensorflow role dep
- name: Add system reqs
  package:
    name:
      - build-essential
#      - libopenblas-base  # In conda as numpy dep in both conda and berryconda
      - python2.7-dev
      - git # should probably put this in with common as a required package...
    install_recommends: no
    autoclean: yes

- name: Add conda reqs
  shell: /opt/conda/bin/conda install -y numpy scipy h5py pyyaml pillow

# Intel math kernel library, only amd64
- name: Add math kernel library for amd64
  shell: /opt/conda/bin/conda install -y mkl-service
  when: RCD_ARCH=="amd64"

- name: Add pip reqs
  pip:
    name:
      - parameterized
      - pydicom
      - ruamel.yaml  # gets rid of a warning about ordereddict
    extra_args: "--no-cache-dir"
    executable: /opt/conda/bin/pip

- set_fact:
    KERAS_VERSION: "2.1.4"
    KERAS_BACKEND: tensorflow

- name: Add Keras environment variables
  lineinfile:
    name: ~/.bashrc
    line: "export KERAS_BACKEND={{KERAS_BACKEND}} MKL_THREADING_LAYER=GNU PYTHONWARNINGS=ignore"
    create: true

- pip:
    name: "git+https://github.com/fchollet/keras.git@{{KERAS_VERSION}}"
    extra_args: "--no-cache-dir --ignore-installed"  #  --no-dependencies
    executable: /opt/conda/bin/pip

- name: Test and print package lists
  shell:
    '/opt/conda/bin/python -W ignore -c "import {{ KERAS_BACKEND }}; print({{ KERAS_BACKEND }}.__version__)" \
     && dpkg-query -l \
     && /opt/conda/bin/pip freeze'
