---
# tasks file for conda


- set_fact:
    CONDA_PKG: "https://repo.continuum.io/miniconda/Miniconda2-4.4.10-Linux-x86_64.sh"
  when: "{{ RCD_ARCH == 'amd64' }}"

- set_fact:
    CONDA_PKG: "https://github.com/jjhelmus/berryconda/releases/download/v2.0.0/Berryconda2-2.0.0-Linux-armv7l.sh"
  when: "{{ RCD_ARCH == 'armv7hf' }}"

- debug:
    msg: "Set CONDA_PKG to {{ CONDA_PKG }}"

- name: Get pkgs
  package:
    name: bzip2

- name: Download Conda
  get_url:
    dest: /tmp/conda.sh
    url: "{{ CONDA_PKG }}"
    mode: 0777
    validate_certs: no

- name: Install Conda
  shell: /tmp/conda.sh -b -f -p /opt/conda

- name: Delete installer
  file:
    name: /tmp/conda.sh
    state: absent

- name: Fix $PATH systemwide with official install tools
  file:
    path: /etc/profile.d/conda.sh
    state: link
    src: /opt/conda/etc/profile.d/conda.sh
  when: "{{ RCD_ARCH == 'amd64' }}"

- name: Fix $PATH for interactive sessions
  lineinfile:
    name: ~/.bashrc
    line: . /opt/conda/etc/profile.d/conda.sh
    create: true

- name: Setup default virtual env for interactive sessions
  lineinfile:
    name: ~/.bashrc
    line: source activate base
    create: true

- name: Update conda
  shell: /opt/conda/bin/conda update -y conda python pip

