---
# tasks file for conda

- set_fact:
    CONDA_PKG: "https://repo.continuum.io/miniconda/Miniconda2-4.4.10-Linux-x86_64.sh"
  when: RCD_ARCH=="amd64"

- set_fact:
    CONDA_PKG: "https://github.com/jjhelmus/berryconda/releases/download/v2.0.0/Berryconda2-2.0.0-Linux-armv7l.sh"
  when: RCD_ARCH=="armv7hf"

- debug:
    msg: "Set CONDA_PKG to {{ CONDA_PKG }}"

- name: Get pkgs
  package:
    name: bzip2

- name: Download Conda
  get_url:
    dest: /tmp/conda.sh
    url: "{{ CONDA_PKG }}"
    mode: 0777
    validate_certs: no

- name: Install Conda
  shell: /tmp/conda.sh -b -f -p /opt/conda

- name: Delete installer
  file:
    name: /tmp/conda.sh
    state: absent

- name: Add conda $PATH for root
  lineinfile:
    name: ~/.bashrc
    line: export PATH=/opt/conda/bin:$PATH
    create: true

# File does not exist on BerryConda
- name: Add profile.d/conda.sh to armv7hf
  copy:
    src: conda.sh
    dest: /opt/conda/etc/profile.d/
  when: RCD_ARCH=="armv7hf"

- name: Setup Conda for interactive sessions
  lineinfile:
    name: ~/.bashrc
    line: . /opt/conda/etc/profile.d/conda.sh
    create: true

- name: Setup Conda for interactive sessions
  file:
    path: /etc/profile.d/conda.sh
    state: link
    src: /opt/conda/etc/profile.d/conda.sh

# Do not use a venv b/c this is a single purpose container
# and it is hard to keep them active in non-interactive
# sessions.

## This is just a convenience so the root env isn't polluted
#- name: Create base env on armv7hf
#  shell: /opt/conda/bin/conda create -n base --clone root
#  when: RCD_ARCH=="armv7hf"

## Only works with official conda package
#- name: Start in default virtual env for interactive sessions
#  lineinfile:
#    name: ~/.bashrc
#    line: source activate base
##  when: RCD_ARCH=="amd64"

- name: Update conda
  shell: /opt/conda/bin/conda update -y conda python

- name: Update pip (conda pip is behind on BerryConda)
  pip:
    name: pip
    extra_args: "--no-cache-dir --upgrade"
    executable: /opt/conda/bin/pip